--1. environment setup
-- Create database and schema
CREATE OR REPLACE DATABASE TITANIC_DB;
USE DATABASE TITANIC_DB;
CREATE OR REPLACE SCHEMA PUBLIC;

-- Create compute warehouse
CREATE OR REPLACE WAREHOUSE TITANIC_WH 
  WITH WAREHOUSE_SIZE='SMALL' 
  AUTO_SUSPEND=60 
  AUTO_RESUME=TRUE;
USE WAREHOUSE TITANIC_WH;

-- Preview raw data
SELECT * FROM TITANIC_DATASET LIMIT 10;

-- Check metadata
SHOW DATABASES LIKE 'TITANIC_DB';
SHOW SCHEMAS IN DATABASE TITANIC_DB;
SHOW WAREHOUSES LIKE 'TITANIC_WH';



-- 2. Data Exploration
-- Missing values check
SELECT 
    SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS missing_age,
    SUM(CASE WHEN FARE IS NULL THEN 1 ELSE 0 END) AS missing_fare,
    SUM(CASE WHEN CABIN IS NULL THEN 1 ELSE 0 END) AS missing_cabin,
    SUM(CASE WHEN EMBARKED IS NULL THEN 1 ELSE 0 END) AS missing_embarked,
    SUM(CASE WHEN SEX IS NULL THEN 1 ELSE 0 END) AS missing_sex
FROM TITANIC_DATASET;

-- Quick stats
SELECT 
    MEDIAN(AGE)   AS median_age,
    AVG(AGE)      AS avg_age,
    STDDEV(AGE)   AS sd_age,
    MEDIAN(FARE)  AS median_fare,
    AVG(FARE)     AS avg_fare,
    STDDEV(FARE)  AS sd_fare
FROM TITANIC_DATASET;

-- Most common embarkation port
SELECT EMBARKED, COUNT(*) AS cnt
FROM TITANIC_DATASET
GROUP BY EMBARKED
ORDER BY cnt DESC
LIMIT 3;



-- 3. Feature Engineering
CREATE OR REPLACE TABLE TITANIC_FEATURES AS
SELECT 
    PASSENGERID,
    SURVIVED,
    CASE WHEN SEX = 'male' THEN 1 WHEN SEX = 'female' THEN 0 END AS SEX_ENCODED,
    PCLASS,
    COALESCE(AGE, 28) AS AGE,
    CASE 
        WHEN COALESCE(AGE, 28) < 18 THEN 'child'
        WHEN COALESCE(AGE, 28) BETWEEN 18 AND 35 THEN 'young_adult'
        WHEN COALESCE(AGE, 28) BETWEEN 36 AND 55 THEN 'adult'
        ELSE 'senior'
    END AS AGE_GROUP,
    (SIBSP + PARCH) AS FAMILY_SIZE,
    CASE 
        WHEN (SIBSP + PARCH) = 0 THEN 'alone'
        WHEN (SIBSP + PARCH) <= 3 THEN 'small_family'
        ELSE 'large_family'
    END AS FAMILY_CATEGORY,
    COALESCE(REGEXP_SUBSTR(NAME, '\\w+\\.'), 'Unknown') AS TITLE,
    COALESCE(FARE, 14.5) / NULLIF((SIBSP + PARCH + 1), 0) AS FARE_PER_PERSON,
    COALESCE(EMBARKED, 'S') AS EMBARKED,
    CASE WHEN CABIN IS NULL THEN 0 ELSE 1 END AS HAS_CABIN
FROM TITANIC_DATASET;
SELECT * FROM TITANIC_FEATURES LIMIT 10;



-- 4. Store in Feature Store
CREATE OR REPLACE SCHEMA FEATURE_STORE;
CREATE OR REPLACE TABLE FEATURE_STORE.TITANIC_FEATURES_FINAL AS
SELECT * FROM TITANIC_FEATURES;
COMMENT ON TABLE FEATURE_STORE.TITANIC_FEATURES_FINAL IS 
'Engineered Titanic dataset ready for ML pipelines';


SHOW TABLES IN SCHEMA FEATURE_STORE;
SELECT * FROM FEATURE_STORE.TITANIC_FEATURES_FINAL LIMIT 10;
